// let API = "http://localhost:3001";
// let API = "http://172.16.20.39:3001";
// let API = "http://20.204.144.125:3001";
// let API = "http://localhost:4001";
// let API = "http://192.168.1.25:4001";
// let API = "http://172.16.20.61:3001";

let API = process.env.REACT_APP_API_KEY;

export const endpoints = {
  getCustomers: `${API}/packcustomers/allcustomers`,
  getCustCodeName: `${API}/packcustomers/allcustcodename`,
  getCustomerDets: `${API}/packcustomers/getcustomer`,
  dueListCustomer: `${API}/packcustomers/customerduelist`,
  overdueListCustomer: `${API}/packcustomers/customeroverduelist`,
  dueSummaryCustomer: `${API}/packcustomers/customerduessummary`,
  receiptsinfoCustomer: `${API}/packcustomers/customerreceiptsinfo`,
  dLInvFormCustomer: `${API}/packcustomers/customerdlinvform`,
  dLInvFormTaxDetsCustomer: `${API}/packcustomers/customerdlinvformtaxdets`,
  receiptDetsCustomer: `${API}/packcustomers/customerreceiptdets`,
  printDueReport: `${API}/packcustomers/printduereport`,
  sendAttachmentMails: `${API}/mailer/sendDirectMail`,

  dxfupload: `${API}/file/uploaddxf`,
  getDwgFiles: `${API}/file/getdxfnames`,

  getStates: `${API}/states/allstates`,
  getStateCode: `${API}/states/getstatecode`,
  getStateName: `${API}/states/getstatename`,
  getCreditTerms: `${API}/creditterms/allcreditterms`,
  getMtrlSources: `${API}/mtrlsources/allmtrlsources`,
  getMtrlTypeLists: `${API}/mtrlgrades/allmtrltypelists`,
  getMtrlGrdTypes: `${API}/mtrlgrades/allmtrlgrdtypes`,
  getMtrlShapes: `${API}/mtrlgrades/allmtrlshapes`,
  getMtrlShapeGrds: `${API}/mtrlgrades/allmtrlshapegrades`,
  saveNewMtrlGrades: `${API}/mtrlgrades/savenewmtrlgrades`,
  getPackingLevels: `${API}/packinglevels/allpackinglevels`,
  getTaxDetails: `${API}/taxdetails/alltaxdetails`,

  getCustBOMParts: `${API}/packcustomers/getcustomerbomparts`,
  assyPartCustomer: `${API}/packcustomers/customerassy`,
  assyInsertPartCustomer: `${API}/packcustomers/customerinsassembly`,
  getCustPartDetails: `${API}/packcustomers/getcustpartdetails`,
  bomAssemblyParts: `${API}/packcustomers/bomassemblyparts`,
  custbomAssemblyParts: `${API}/packcustomers/custbomassemblyparts`,
  UpdateBOMAssembly: `${API}/packcustomers/updatebomassembly`,
  DeleteBOMAssemblyPart: `${API}/packcustomers/deletebomassmparts`,
  saveCustBOMParts: `${API}/packcustomers/custbomparts`,
  chkAssyDupl: `${API}/packcustomers/chkassydupl`,

  scheduleTasksCustomer: `${API}/packcustomers/schtasksdets`,
  drawingsCustomer: `${API}/packcustomers/packcustomersdrawings`,
  ordStatusCustomer: `${API}/packcustomers/orderstatus`,
  ordersCustomer: `${API}/packcustomers/customerorders`,
  orderScheduleCustomer: `${API}/packcustomers/orderschedule`,
  orderInvoicesCustomer: `${API}/packcustomers/orderinvoices`,
  orderDetailsCustomer: `${API}/packcustomers/orderdetails`,
  ordSchTasksCustomer: `${API}/packcustomers/orderschtasks`,
  schDetsCustomer: `${API}/packcustomers/schdets`,
  invDwgCustomer: `${API}/packcustomers/orderinvdwg`,
  updateCustomer: `${API}/packcustomers/customerupdate`,
  insertContactTeleNos: `${API}/packcustomers/insertcontacttelenos`,
  getCustomerDetails: `${API}/packcustomers/getcustomerdetails`,
  createCustomer: `${API}/packcustomers/customer`,

  getCustomerContactDets: `${API}/packcustomers/getcustomercontactdets`,
  getCustomerContactTeleDets: `${API}/packcustomers/getcustomercontactteledets`,
  outStandingCustomers: `${API}/packcustomers/customeroutstandings`,
  individualCustomer: `${API}/packcustomers/outstandinginvoices`,
  pprDueListCustomer: `${API}/packcustomers/pprcustomerduelist`,
  getCustDuesOverdues: `${API}/packcustomers/customerduesoverdues`,

  mtrlStockCustomer: `${API}/packcustomers/customermtrlstock`,
  mtrlReceiptsCustomer: `${API}/packcustomers/customermtrlreceipts`,
  mtrlPartsReturnedCustomer: `${API}/packcustomers/customermtrlpartsreturned`,
  mtrlScrapUnusedReturnedCustomer: `${API}/packcustomers/customermtrlscrapUnusedreturned`,
  mtrlReceiptDetailsCustomer: `${API}/packcustomers/customermtrlrectdetails`,
  getCustPartRects: `${API}/packcustomers/getcustpartrects`,
  getMtrlRVList: `${API}/packcustomers/getmtrlrvlist`,

  getMaterials: `${API}/materials/allmaterials`,
  getProcessLists: `${API}/processlists/allprocesslists`,
  getMtrlGrades: `${API}/mtrlgrades/allmtrlgrades`,
  getToleranceTypes: `${API}/tolerancetypes/alltolerancetypes`,
  getInspectionLevels: `${API}/inspectionlevels/allinspectionlevels`,
  getMtrlGrade: `${API}/mtrlgrades/mtrlgrad`,
  getMaterialSpWt: `${API}/mtrlgrades/getmaterialspwt`,

  createQuotation: `${API}/quotation/quotation`,
  getQuotations: `${API}/quotation/getquotations`,
  getQuotationList: `${API}/quotation/getquotationlist`,
  qtnStatusUpdate: `${API}/quotation/quotationstatusupdate`,
  getQtnRejnReasons: `${API}/quotation/getqtnrejnreasons`,
  saveQtnTaskListDetails: `${API}/quotation/saveqtntasklistdets`,
  saveProfileListdata: `${API}/quotation/saveprofilelistdata`,
  saveTaskDetails: `${API}/quotation/savetaskdetails`,
  getTaskMaterialRates: `${API}/quotation/gettaskmaterialrates`,
  getOperationMtrlRateList: `${API}/quotation/getoperationmtrlratelist`,
  getMtrlHandlingRates: `${API}/quotation/getmtrlhandlingrates`,
  getTaskProgrammingRates: `${API}/quotation/gettaskprogrammingrates`,
  UpdateProfileDetails: `${API}/quotation/updateprofiledetails`,
  //getTaxDetails: `${API}/taxdetails/alltaxdetails`,
  getQtntcDetails: `${API}/quotation/getqtntcdetails`,
  getQtnTaxDetails: `${API}/quotation/getqtntaxdetails`,
  getQuotationItems: `${API}/quotation/getquotationitems`,
  getTermsConditions: `${API}/termsconditions/alltermsconditions`,
  saveQuotationItems: `${API}/quotation/quotationitemslist`,
  updateQuotation: `${API}/quotation/updatequotation`,
  qtnItemsDeleteandSave: `${API}/quotation/qtnitemsdeleteandsave`,
  deleteQtnItemData: `${API}/quotation/deleteqtnitemdata`,
  qtnItemsDeletedSave: `${API}/quotation/qtnitemsdeletedsave`,
  getEstimateList: `${API}/quotation/getestimate`,
  getSelectedQuotation: `${API}/quotation/getselectedquotation`,
  ChkQtnItems: `${API}/quotation/chkQtnItems`,
  SaveFabAssyParts: `${API}/quotation/savefabassyparts`,

  getMtrlDetails: `${API}/materials/getmtrldetails`,
  getMtrlLocation: `${API}/materials/getmtrllocation`,
  getOrderSchedule: `${API}/sigmanc/getorderschedule`,
  getNCTaskList: `${API}/sigmanc/getnctasklist`,
  getNCTaskParts: `${API}/sigmanc/getnctaskparts`,
  getProgramListData: `${API}/sigmanc/getprogramlistdata`,
  getMtrlAvailability: `${API}/sigmanc/getmtrlavailability`,
  updateProgramStatus: `${API}/sigmanc/updateprogramstatus`,
  getMachineDetails: `${API}/machine/allmachines`,

  getProdSchListDetails: `${API}/production/getprodschlistdetails`,
  getNCProgramListData: `${API}/production/getncprogramlistdata`,

  getOrderData: `${API}/order/getorderdata`,
  getOrdDetailsData: `${API}/order/getorddetailsdata`,
  getSalesExecLists: `${API}/salesexecutives/allsalesexeclists`,
  getSalesIndiExecLists: `${API}/salesexecutives/indisalesexeclists`,
  getCombinedTaskSch: `${API}/order/getcombinedschdata`,
  getOrderScheduleData: `${API}/order/getorderscheduledata`,
  getSelectedSchDwgData: `${API}/order/getselectedschdwgdata`,
  getSalesTasksData: `${API}/order/getsalestasksdata`,
  getSelectedSalesTaskList: `${API}/order/getselectedsalestasklist`,
  getPrepareScheduleDetails: `${API}/order/preparescheduledetails`,
  createOrder: `${API}/order/createorder`,

  getPackScheduleDetails: `${API}/packinv/getpackingschedules`,
  getPackSchDetails: `${API}/packinv/getpackschdetails`,
  getExNotifDetails: `${API}/packinv/getexnotifications`,
  getPckScheduleDetails: `${API}/packinv/getpckscheduledetails`,

  getMtrlStocks: `${API}/stocks/getmtrlstocks`,
  getMtrlCodeStocks: `${API}/stocks/getmtrlcodestocks`,
  getMtrlStocksDets: `${API}/stocks/getmtrlstocksdets`,
  getStockArrivalSummary: `${API}/stocks/getstockarrivalsummary`,
  getStockArrivalReceipts: `${API}/stocks/getstockarrivalreceipts`,
  getStockArrivalReceiptList: `${API}/stocks/getstockarrivalreceiptList`,

  getSalesDispatchSummary: `${API}/stocks/getsalesdispatchsummary`,
  getSalesDispatchInvoices: `${API}/stocks/getsalesdispatchinvoices`,
  getSalesDispatchStockList: `${API}/stocks/getsalesdispatchstocklist`,

  getUserRoles: `${API}/packuser/getuserroles`,
  addUserRoles: `${API}/packuser/adduserroles`,
  updUserRoles: `${API}/packuser/upduserroles`,
  delUserRoles: `${API}/packuser/deluserroles`,
  getUserModules: `${API}/packuser/getusermodules`,
  addUserModules: `${API}/packuser/addusermodules`,
  getUserMenus: `${API}/packuser/getusermenus`,
  getUsers: `${API}/packuser/getusers`,
  addUserMenus: `${API}/packuser/addusermenus`,
  delUserMenus: `${API}/packuser/delusermenus`,
  getUnits: `${API}/packunits/allunits`,
  saveUsers: `${API}/packuser/saveusers`,
  delUsers: `${API}/packuser/delusers`,
  loginAPI: `${API}/packuser/login`,
  saveMenuRoleMapping: `${API}/packuser/savemenurolemapping`,
  getRoleMenus: `${API}/packuser/getrolemenus`,

  getDlyRepSales: `${API}/accounts/salesinvoices`,
  getTaxSummary: `${API}/accounts/taxsummary`,
  getPaymentReceipts: `${API}/accounts/paymentreceipts`,
  getPaymentRectsDetails: `${API}/accounts/paymentrectdetails`,
  getPrdSummary: `${API}/accounts/prdsummary`,

  toCheckBomParts: `${API}/packcustomers/checkbomassmparts`,
  //Paking And Invoice
  getData: `${API}/gettest/getdata`,
  getCustomerData: `${API}/schedulelist/getallcustomers`,
};
